version: '3'

services:
  nextclouddatabase:
    image: mariadb:10.5
    container_name: nextcloudDatabase
    command: ["--transaction-isolation=READ-COMMITTED", "--binlog-format=ROW"]
    volumes:
      - nextcloud_database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=passwd123
      - MYSQL_PASSWORD=passwd123
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    restart: unless-stopped

  nextcloudredis:
    image: redis:alpine
    container_name: nextcloudRedis
    restart: unless-stopped
    command: redis-server --requirepass redispassword

  nextcloudapp:
    image: nextcloud:26-fpm-alpine
    container_name: nextcloudApp
    links:
      - nextclouddatabase
      - nextcloudredis
    ports:
      - 8080:80
    volumes:
      - nextcloud_app:/var/www/html:rw
#      - ./website1:/var/www/html:rw
      - /media/szymon/data1/nc26data:/var/www/html/data:rw
#      - ./config/config.php:/var/www/html/config/config.php:rw
    environment:
      - MYSQL_PASSWORD=passwd123
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextclouddatabase
      - REDIS_HOST_PASSWORD=redispassword
      - TRUSTED_PROXIES=172.19.0.240 # IP address of nginx-proxy
      - NEXTCLOUD_TRUSTED_DOMAINS=dysk.paczos.org
    depends_on:
      - nextclouddatabase
      - nextcloudredis
    restart: unless-stopped

  nextcloudweb:
    container_name: nextcloudWeb
    build:
      context: ./web
    restart: unless-stopped
    ports:
      - "81:80"
    volumes:
      - nextcloud_app:/var/www/html:rw
#      - ./website1:/var/www/html:rw
#      - /var/log/nginx/error.log LOGS
#      - ./nginx/:/etc/nginx:rw
    environment:
      - NGINX_PORT=80
#      - LETSENCRYPT_HOST=
#      - LETSENCRYPT_EMAIL=
    networks:
      default:
        ipv4_address: 172.19.0.23
        aliases:
          - nextcloudweb
    depends_on:
      - nextcloudapp

#  nextcloudphpmyadmin:
#    container_name: nextcloudPHPMyAdmin
#    image: phpmyadmin:5
#    environment:
#      PMA_HOST: "nextclouddatabase"
#      MYSQL_ROOT_PASSWORD: "passwd123"
#    ports:
#      - '8081:80'
#    networks:
#      backend:
#        ipv4_address: 172.28.0.30
#        aliases:
#          - phpmyadmin
#    restart: unless-stopped

#  collabora:
#    image: collabora/code
#    container_name: collabora
#    ports:
#      - 9980:9980
#    cap_add:
#      - MKNOD
#    environment:
#      - domain=example\\.domain\\.com
#      - VIRTUAL_HOST=offices.ydns.eu
#      - VIRTUAL_NETWORK=nginx-proxy
#      - extra_params=--o:ssl.enable=false --o:ssl.termination=false
#      - LETSENCRYPT_HOST=offices.domain.com
#      - LETSENCRYPT_EMAIL=example@com.com
#      - username=collabora
#      - password=collabora
#    networks:
#      - nextcloud_network
#    restart: always
#    expose:
#      - '80'
#      - '443'

  nextcloudoffice:
    image: collabora/code
    container_name: nextcloudoffice
    hostname: nextcloudoffice
    restart: unless-stopped
    cap_add:
      - MKNOD
    environment:
      - domain=dysk.paczos.org
      - "extra_params=--o:ssl.enable=false --o:ssl.termination=false"
    networks:
      default:
        ipv4_address: 172.19.0.22
        aliases:
          - nextcloudoffice


volumes:
  nextcloud_app:
  nextcloud_database:
  postgresql_data:

networks:
  default:
    external:
      name: common-network
