version: '3'

services:
  nextcloud_database:
    image: mariadb:10.5
    container_name: nextcloud_database
    restart: always
    command: ["--transaction-isolation=READ-COMMITTED", "--binlog-format=ROW"]
    volumes:
      - nextcloud_database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=passwd123
      - MYSQL_PASSWORD=passwd123
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MARIADB_AUTO_UPGRADE=1
      - MARIADB_DISABLE_UPGRADE_BACKUP=1
    restart: always

  nextcloud_redis:
    image: redis:alpine
    container_name: nextcloud_redis
    restart: always
    command: redis-server --requirepass redispassword

  nextcloud_app:
    image: nextcloud:25-fpm-alpine
    container_name: nextcloud_app
    links:
      - nextcloud_database
      - nextcloud_redis
    ports:
      - 8080:80
    volumes:
      - nextcloud_app:/var/www/html:rw
      - /media/szymon/data/nc25data:/var/www/html/data:rw
    environment:
      - MYSQL_PASSWORD=passwd123
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud_database
      - REDIS_HOST_PASSWORD=redispassword
#      - VIRTUAL_HOST=dysk.paczos.org
#      - LETSENCRYPT_HOST=dysk.paczos.org
#      - VIRTUAL_PORT=9000
#      - TRUSTED_PROXIES=dysk.paczos.org
#      - APACHE_DISABLE_REWRITE_IP=1
    depends_on: 
      - nextcloud_database
      - nextcloud_redis
    restart: always

  nextcloud_web:
    build: ./web/dockerfile
    restart: always
    volumes:
      - nextcloud_app:/var/www/html:ro
#    environment:
#      - VIRTUAL_HOST=
#      - LETSENCRYPT_HOST=
#      - LETSENCRYPT_EMAIL=
    depends_on:
      - nextcloud_app

#  collabora:
#    image: collabora/code
#    container_name: collabora
#    ports:
#      - 9980:9980
#    cap_add:
#      - MKNOD
#    environment:
#      - domain=example\\.domain\\.com
#      - VIRTUAL_HOST=offices.ydns.eu
#      - VIRTUAL_NETWORK=nginx-proxy
#      - extra_params=--o:ssl.enable=false --o:ssl.termination=false
#      - LETSENCRYPT_HOST=offices.domain.com
#      - LETSENCRYPT_EMAIL=example@com.com
#      - username=collabora
#      - password=collabora
#    networks:
#      - nextcloud_network
#    restart: always
#    expose:
#      - '80'
#      - '443'

#  nextcloudoffice:
#    image: collabora/code
#    container_name: nextcloudoffice
#    hostname: nextcloudoffice
#    restart: unless-stopped
#    cap_add:
#      - MKNOD
#    environment:
#      domain: "dysk.paczos.org"

volumes:
  nextcloud_app:
  nextcloud_database:
  postgresql_data:

networks: 
  default: 
    external: 
      name: common-network 
