FROM nginx:alpine
COPY old.conf /etc/nginx/nginx.conf
#TODO redesign nginx conf
#COPY nginx.conf /etc/nginx/nginx.conf
#COPY default.conf /etc/nginx/conf.d/default.conf

#templates needs nginx 1.19+
#COPY nextcloudapp.conf /etc/nginx/templates/nextcloudapp.conf.template      
